server :
  port: 8000

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/moduedu
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 3157
    jpa:
      open-in-view: false
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

