server :
  port: 8000

spring:
  datasource:
    url: jdbc:mariadb://ec2-3-36-217-12.ap-northeast-2.compute.amazonaws.com:3306/moduedu
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: moduedu123!@#
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true # mysql debug mode, 실제 쿼리가 로그로 보임
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate: # custom options
        format_sql: true # sql 로그를 포매팅해서 보여줌
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

