server :
  port: 8000

spring:
  datasource:
    url: jdbc:mariadb://ec2-3-36-217-12.ap-northeast-2.compute.amazonaws.com:3306/moduedu
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: moduedu123!@#
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          use-new-id-generator-mappings: false
      show-sql: true
      properties:
        hibernate.enable_lazy_load_no_trans: true
        hibernate.format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

